name: Unit tests (without integration)

#This workflow will load Pillar and launch all tests except the integration tests that are using archetypes and requiring latex.

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. 
on: [ push, pull_request ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: Pharo64-11
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }} .smalltalk.Unit.ston
        shell: bash
        timeout-minutes: 15
